// New question:
export const EDIT_QUESTION_TITLE = 'EDIT_QUESTION_TITLE';
export const CLEAN_QUESTION = 'CLEAN_QUESTION';
export const ADD_QUESTION_CHOICE = 'ADD_QUESTION_CHOICE';
export const EDIT_QUESTION_CHOICE = 'EDIT_QUESTION_CHOICE';
export const DELETE_QUESTION_CHOICE = 'DELETE_QUESTION_CHOICE';
export const TOGGLE_QUESTION_OPTION = 'TOGGLE_QUESTION_OPTION';


// Authentication:
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';

// Questions:
export const GET_QUESTIONS = 'GET_QUESTIONS';

// Current question:
export const GET_QUESTION = 'GET_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const ADD_QUESTION_VOTE = 'ADD_QUESTION_VOTE';
export const SET_QUESTION_VOTE = 'SET_QUESTION_VOTE';
export const REMOVE_QUESTION_VOTE = 'REMOVE_QUESTION_VOTE';
export const VOTE_ON_QUESTION = 'VOTE_ON_QUESTION';
