export const EDIT_QUESTION_TITLE = 'EDIT_QUESTION_TITLE';
export const ADD_QUESTION_CHOICE = 'ADD_QUESTION_CHOICE';
export const EDIT_QUESTION_CHOICE = 'EDIT_QUESTION_CHOICE';
export const DELETE_QUESTION_CHOICE = 'DELETE_QUESTION_CHOICE';
