// New question:
export const EDIT_QUESTION_TITLE = 'EDIT_QUESTION_TITLE';
export const CLEAN_QUESTION = 'CLEAN_QUESTION';
export const ADD_QUESTION_CHOICE = 'ADD_QUESTION_CHOICE';
export const EDIT_QUESTION_CHOICE = 'EDIT_QUESTION_CHOICE';
export const DELETE_QUESTION_CHOICE = 'DELETE_QUESTION_CHOICE';

// Authentication:
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';

// Questions from db:
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
